---
kind: pipeline
type: docker
name: cross

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare
    image: library/alpine:3.14
    environment:
      GOLANG: golang:1.16-alpine3.14
      IMAGE: drone.cattle.io/rancher/kim
    commands:
      - "apk --no-cache add docker-cli git"
      - "docker build --target docker --build-arg GOLANG --tag $${IMAGE}:possible --tag $${IMAGE}:$(git rev-parse --short HEAD) ."
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: bin-dist
    image: drone.cattle.io/rancher/kim:possible
    pull: never
    environment:
      DOCKER_BUILDKIT: "1"
      GOLANG: drone.cattle.io/rancher/kim:possible
    commands:
      - make GOOS=linux   GOARCH=amd64    TAG=${DRONE_TAG:-$(git describe --tags --always)} dist
      - make GOOS=linux   GOARCH=arm64    TAG=${DRONE_TAG:-$(git describe --tags --always)} dist
      - make GOOS=linux   GOARCH=arm      TAG=${DRONE_TAG:-$(git describe --tags --always)} dist
      - make GOOS=linux   GOARCH=s390x    TAG=${DRONE_TAG:-$(git describe --tags --always)} dist
      - make GOOS=linux   GOARCH=ppc64le  TAG=${DRONE_TAG:-$(git describe --tags --always)} dist
      - make GOOS=darwin  GOARCH=amd64    TAG=${DRONE_TAG:-$(git describe --tags --always)} dist
      - make GOOS=darwin  GOARCH=arm64    TAG=${DRONE_TAG:-$(git describe --tags --always)} dist
      - make GOOS=windows GOARCH=amd64    TAG=${DRONE_TAG:-$(git describe --tags --always)} dist
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: img-dist
    image: drone.cattle.io/rancher/kim:possible
    pull: never
    environment:
      DOCKER_BUILDKIT: "1"
      GOLANG: drone.cattle.io/rancher/kim:possible
    commands:
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} GOARCH=amd64   image-dist
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} GOARCH=arm64   image-dist
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} GOARCH=arm     image-dist
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} GOARCH=ppc64le image-dist
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} GOARCH=s390x   image-dist
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: bin-upload
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - sha256
      checksum_file: CHECKSUMsum.txt
      checksum_flatten: true
      files:
        - dist/artifacts/*
      prerelease: true
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*

  - name: img-push
    image: drone.cattle.io/rancher/kim:possible
    pull: never
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_BUILDKIT: "1"
      GOLANG: drone.cattle.io/rancher/kim:possible
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} GOARCH=amd64   image-push
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} GOARCH=arm64   image-push
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} GOARCH=arm     image-push
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} GOARCH=ppc64le image-push
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} GOARCH=s390x   image-push
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: manifest

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare
    image: library/alpine:3.14
    environment:
      GOLANG: golang:1.16-alpine3.14
      IMAGE: drone.cattle.io/rancher/kim
    commands:
      - "apk --no-cache add docker-cli git"
      - "docker build --target docker --build-arg GOLANG --tag $${IMAGE}:possible --tag $${IMAGE}:$(git rev-parse --short HEAD) ."
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: manifest-all
    image: drone.cattle.io/rancher/kim:possible
    pull: never
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_BUILDKIT: "1"
      GOLANG: drone.cattle.io/rancher/kim:possible
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - make TAG=${DRONE_TAG:-$(git describe --tags --always)} image-manifest-all
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

depends_on:
  - cross

...
